version: '3.7'

services:
  postgresql:
    image: postgres:11.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: danieldisu
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: hnnotify