spring:

  datasource:
    hikari:
      maximumPoolSize: 5

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


hnnotify:
  initialDelay: 30000
  maxStoriesToFetch: 30
  timeBetweenFetches: 30000
