spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        temp:
          use_jdbc_metadata_defaults: false
      jdbc:
        lob:
          non_contextual_creation: true

hnnotify:
  initialDelay: 60000 # 1 minute
  maxStoriesToFetch: 500
  timeBetweenFetches: 3600000 # 1 hour
