spring:

  datasource:
    hikari:
      maximumPoolSize: 5

  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect


hnnotify:
  initialDelay: 30000
  maxStoriesToFetch: 20
  timeBetweenFetches: 30000
  cleanup:
    targetNumberOfRows: 9000
    timeBetween: 300000
    initialDelay: 5000
