spring:
  datasource:
    url: jdbc:postgresql://${docker.host}:5432/hnnotify
    username: danieldisu
    password: 123456
    platform: postgres
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        temp:
          use_jdbc_metadata_defaults: false
      jdbc:
        lob:
          non_contextual_creation: true
