spring:

  datasource:
    hikari:
      maximumPoolSize: 5

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


hnnotify:
  initialDelay: 30000
  maxStoriesToFetch: 500
  timeBetweenFetches: 3600000 # 1 hour
