spring:

  main:
    banner-mode: console

  datasource:
    url: jdbc:postgresql://localhost:5432/hnnotify
    username: danieldisu
    password: 123456

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

hnnotify:
  initialDelay: 1000
  maxStoriesToFetch: 10
  timeBetweenFetches: 60000
